# Credit Risk Classification

Credit risk poses a classification problem that’s inherently imbalanced. This is because healthy loans easily outnumber risky loans. In this Challenge, you’ll use various techniques to train and evaluate models with imbalanced classes. You’ll use a dataset of historical lending activity from a peer-to-peer lending services company to build a model that can identify the creditworthiness of borrowers.

## Instructions:

This challenge consists of the following subsections:

* Split the Data into Training and Testing Sets

* Create a Logistic Regression Model with the Original Data

* Predict a Logistic Regression Model with Resampled Training Data 

### Split the Data into Training and Testing Sets

Open the starter code notebook and then use it to complete the following steps.

1. Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

2. Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

    > **Note** A value of `0` in the “loan_status” column means that the loan is healthy. A value of `1` means that the loan has a high risk of defaulting.  

3. Check the balance of the labels variable (`y`) by using the `value_counts` function.

4. Split the data into training and testing datasets by using `train_test_split`.

### Create a Logistic Regression Model with the Original Data

Employ your knowledge of logistic regression to complete the following steps:

1. Fit a logistic regression model by using the training data (`X_train` and `y_train`).

2. Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

3. Evaluate the model’s performance by doing the following:

    * Calculate the accuracy score of the model.

    * Generate a confusion matrix.

    * Print the classification report.

4. Answer the following question: How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

### Predict a Logistic Regression Model with Resampled Training Data

Did you notice the small number of high-risk loan labels? Perhaps, a model that uses resampled data will perform better. You’ll thus resample the training data and then reevaluate the model. Specifically, you’ll use `RandomOverSampler`.

To do so, complete the following steps:

1. Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

2. Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

3. Evaluate the model’s performance by doing the following:

    * Calculate the accuracy score of the model.

    * Generate a confusion matrix.

    * Print the classification report.
    
4. Answer the following question: How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

### Write a Credit Risk Analysis Report

For this section, you’ll write a brief report that includes a summary and an analysis of the performance of both machine learning models that you used in this challenge. You should write this report as the `README.md` file included in your GitHub repository.

Structure your report by using the report template that `Starter_Code.zip` includes, and make sure that it contains the following:

1. An overview of the analysis: Explain the purpose of this analysis.


2. The results: Using bulleted lists, describe the balanced accuracy scores and the precision and recall scores of both machine learning models.

3. A summary: Summarize the results from the machine learning models. Compare the two versions of the dataset predictions. Include your recommendation for the model to use, if any, on the original vs. the resampled data. If you don’t recommend either model, justify your reasoning.

In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

import warnings
warnings.filterwarnings('ignore')

C:\Users\nehaja\Anaconda3\envs\dev\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\nehaja\Anaconda3\envs\dev\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
C:\Users\nehaja\Anaconda3\envs\dev\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
df = pd.read_csv(Path("./Resources/lending_data.csv"))

# Review the DataFrame
df

,loan_size,interest_rate,borrower_income,debt_to_income,num_of_accounts,derogatory_marks,total_debt,loan_status
0,10700.0,7.672,52800,0.431818,5,1,22800,0
1,8400.0,6.692,43600,0.311927,3,0,13600,0
2,9000.0,6.963,46100,0.349241,3,0,16100,0
3,10700.0,7.664,52700,0.430740,5,1,22700,0
4,10800.0,7.698,53000,0.433962,5,1,23000,0
5,10100.0,7.438,50600,0.407115,4,1,20600,0
6,10300.0,7.490,51100,0.412916,4,1,21100,0
7,8800.0,6.857,45100,0.334812,3,0,15100,0
8,9300.0,7.096,47400,0.367089,3,0,17400,0
9,9700.0,7.248,48800,0.385246,4,0,18800,0
10,9300.0,7.085,47300,0.365751,3,0,17300,0
11,9200.0,7.015,46600,0.356223,3,0,16600,0
12,9200.0,7.043,46900,0.360341,3,0,16900,0
13,9400.0,7.101,47400,0.367089,3,0,17400,0
14,8400.0,6.703,43700,0.313501,3,0,13700,0
15,9400.0,7.136,47700,0.371069,3,0,17700,0
16,8900.0,6.897,45500,0.340659,3,0,15500,0
17,8300.0,6.648,43200,0.305556,2,0,13200,0
18,8000.0,6.539,42100,0.287411,2,0,12100,0
19,10200.0,7.460,50800,0.409449,4,1,20800,0
20,5200.0,5.326,30700,0.022801,0,0,700,0
21,9300.0,7.068,47100,0.363057,3,0,17100,0
22,7300.0,6.225,39200,0.234694,2,0,9200,0
23,9000.0,6.943,45900,0.346405,3,0,15900,0
24,8700.0,6.813,44700,0.328859,3,0,14700,0
25,8800.0,6.850,45100,0.334812,3,0,15100,0
26,8400.0,6.700,43700,0.313501,3,0,13700,0
27,7900.0,6.482,41600,0.278846,2,0,11600,0
28,9700.0,7.267,49000,0.387755,4,0,19000,0
29,8400.0,6.700,43600,0.311927,3,0,13600,0
...,...,...,...,...,...,...,...,...
77506,18100.0,10.801,82200,0.635036,11,2,52200,1
77507,18700.0,11.087,84900,0.646643,12,2,54900,1
77508,21900.0,12.426,97500,0.692308,15,3,67500,1
77509,19900.0,11.565,89400,0.664430,13,2,59400,1
77510,17000.0,10.356,78100,0.615877,10,2,48100,1
77511,15900.0,9.872,73500,0.591837,9,2,43500,1
77512,19200.0,11.265,86600,0.653580,12,2,56600,1
77513,20600.0,11.881,92400,0.675325,14,3,62400,1
77514,16600.0,10.169,76300,0.606815,10,2,46300,1
77515,18600.0,11.045,84500,0.644970,12,2,54500,1
77516,19700.0,11.509,88900,0.662542,13,2,58900,1
77517,18100.0,10.836,82600,0.636804,11,2,52600,1
77518,20300.0,11.747,91200,0.671053,13,3,61200,1
77519,17200.0,10.437,78800,0.619289,10,2,48800,1
77520,21400.0,12.216,95600,0.686192,14,3,65600,1
77521,20900.0,12.020,93700,0.679829,14,3,63700,1
77522,21700.0,12.363,96900,0.690402,15,3,66900,1
77523,20400.0,11.813,91800,0.673203,13,3,61800,1
77524,16900.0,10.302,77500,0.612903,10,2,47500,1
77525,20300.0,11.753,91200,0.671053,13,3,61200,1
77526,18300.0,10.895,83100,0.638989,11,2,53100,1
77527,20900.0,11.988,93400,0.678801,14,3,63400,1
77528,15100.0,9.557,70500,0.574468,9,2,40500,1
77529,19300.0,11.347,87400,0.656751,12,2,57400,1
77530,19700.0,11.508,88900,0.662542,13,2,58900,1
77531,19100.0,11.261,86600,0.653580,12,2,56600,1
77532,17700.0,10.662,80900,0.629172,11,2,50900,1
77533,17600.0,10.595,80300,0.626401,11,2,50300,1
77534,16300.0,10.068,75300,0.601594,10,2,45300,1
77535,15600.0,9.742,72300,0.585062,9,2,42300,1

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [6]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = df["loan_status"]

# Separate the X variable, the features
X = df.drop(columns="loan_status")

In [7]:
# Review the y variable Series
y

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
77506    1
77507    1
77508    1
77509    1
77510    1
77511    1
77512    1
77513    1
77514    1
77515    1
77516    1
77517    1
77518    1
77519    1
77520    1
77521    1
77522    1
77523    1
77524    1
77525    1
77526    1
77527    1
77528    1
77529    1
77530    1
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64

In [8]:
# Review the X variable DataFrame
X

,loan_size,interest_rate,borrower_income,debt_to_income,num_of_accounts,derogatory_marks,total_debt
0,10700.0,7.672,52800,0.431818,5,1,22800
1,8400.0,6.692,43600,0.311927,3,0,13600
2,9000.0,6.963,46100,0.349241,3,0,16100
3,10700.0,7.664,52700,0.430740,5,1,22700
4,10800.0,7.698,53000,0.433962,5,1,23000
5,10100.0,7.438,50600,0.407115,4,1,20600
6,10300.0,7.490,51100,0.412916,4,1,21100
7,8800.0,6.857,45100,0.334812,3,0,15100
8,9300.0,7.096,47400,0.367089,3,0,17400
9,9700.0,7.248,48800,0.385246,4,0,18800
10,9300.0,7.085,47300,0.365751,3,0,17300
11,9200.0,7.015,46600,0.356223,3,0,16600
12,9200.0,7.043,46900,0.360341,3,0,16900
13,9400.0,7.101,47400,0.367089,3,0,17400
14,8400.0,6.703,43700,0.313501,3,0,13700
15,9400.0,7.136,47700,0.371069,3,0,17700
16,8900.0,6.897,45500,0.340659,3,0,15500
17,8300.0,6.648,43200,0.305556,2,0,13200
18,8000.0,6.539,42100,0.287411,2,0,12100
19,10200.0,7.460,50800,0.409449,4,1,20800
20,5200.0,5.326,30700,0.022801,0,0,700
21,9300.0,7.068,47100,0.363057,3,0,17100
22,7300.0,6.225,39200,0.234694,2,0,9200
23,9000.0,6.943,45900,0.346405,3,0,15900
24,8700.0,6.813,44700,0.328859,3,0,14700
25,8800.0,6.850,45100,0.334812,3,0,15100
26,8400.0,6.700,43700,0.313501,3,0,13700
27,7900.0,6.482,41600,0.278846,2,0,11600
28,9700.0,7.267,49000,0.387755,4,0,19000
29,8400.0,6.700,43600,0.311927,3,0,13600
...,...,...,...,...,...,...,...
77506,18100.0,10.801,82200,0.635036,11,2,52200
77507,18700.0,11.087,84900,0.646643,12,2,54900
77508,21900.0,12.426,97500,0.692308,15,3,67500
77509,19900.0,11.565,89400,0.664430,13,2,59400
77510,17000.0,10.356,78100,0.615877,10,2,48100
77511,15900.0,9.872,73500,0.591837,9,2,43500
77512,19200.0,11.265,86600,0.653580,12,2,56600
77513,20600.0,11.881,92400,0.675325,14,3,62400
77514,16600.0,10.169,76300,0.606815,10,2,46300
77515,18600.0,11.045,84500,0.644970,12,2,54500
77516,19700.0,11.509,88900,0.662542,13,2,58900
77517,18100.0,10.836,82600,0.636804,11,2,52600
77518,20300.0,11.747,91200,0.671053,13,3,61200
77519,17200.0,10.437,78800,0.619289,10,2,48800
77520,21400.0,12.216,95600,0.686192,14,3,65600
77521,20900.0,12.020,93700,0.679829,14,3,63700
77522,21700.0,12.363,96900,0.690402,15,3,66900
77523,20400.0,11.813,91800,0.673203,13,3,61800
77524,16900.0,10.302,77500,0.612903,10,2,47500
77525,20300.0,11.753,91200,0.671053,13,3,61200
77526,18300.0,10.895,83100,0.638989,11,2,53100
77527,20900.0,11.988,93400,0.678801,14,3,63400
77528,15100.0,9.557,70500,0.574468,9,2,40500
77529,19300.0,11.347,87400,0.656751,12,2,57400
77530,19700.0,11.508,88900,0.662542,13,2,58900
77531,19100.0,11.261,86600,0.653580,12,2,56600
77532,17700.0,10.662,80900,0.629172,11,2,50900
77533,17600.0,10.595,80300,0.626401,11,2,50300
77534,16300.0,10.068,75300,0.601594,10,2,45300
77535,15600.0,9.742,72300,0.585062,9,2,42300

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [9]:
# Check the balance of our target values
y.value_counts()

0    75036
1     2500
Name: loan_status, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [11]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [12]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_regression_model = LogisticRegression(random_state=1)

# Fit the model using training data

logistic_regression_model.fit(X_train, y_train)

LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [13]:
# Make a prediction using the testing data
testing_predictions = logistic_regression_model.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [25]:
# Print the balanced_accuracy score of the model
balanced_accuracy_score(y_test, testing_predictions)

0.9520479254722232

In [18]:
# Generate a confusion matrix for the model
training_matrix = confusion_matrix(y_test, testing_predictions)
print(training_matrix)

[[18663   102]
 [   56   563]]

In [19]:
# Import the module
from sklearn.metrics import classification_report
# Print the classification report for the model
training_report = classification_report(y_test, testing_predictions)
# Then view its output
print(training_report)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384

### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** WRITE YOUR ANSWER HERE!

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points.

In [20]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
random_oversampler = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
X_resampled, y_resampled = random_oversampler.fit_resample(X_train, y_train)

In [21]:
# Count the distinct values of the resampled labels data
y_resampled.value_counts()

1    56271
0    56271
Name: loan_status, dtype: int64

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [23]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
model = LogisticRegression(random_state=1)

# Fit the model using the resampled training data
model.fit(X_resampled, y_resampled)

# Make a prediction using the testing data
y_pred = model.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [24]:
# Print the balanced_accuracy score of the model 
balanced_accuracy_score(y_test, y_pred)

0.9936781215845847

In [26]:
# Generate a confusion matrix for the model
print(confusion_matrix(y_test, y_pred))

[[18649   116]
 [    4   615]]

In [27]:
# Print the classification report for the model
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.99      0.99      1.00      0.99      0.99     18765
          1       0.84      0.99      0.99      0.91      0.99      0.99       619

avg / total       0.99      0.99      0.99      0.99      0.99      0.99     19384

### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** 
The results regarding the accuracy of the minorty class are actually mixed when  comparing the classification reports generated from the predictions with the original data versus the predictions with teh resample data. First, teh accuracy score is much higher for the resample data. Meaning that the model of using the resample data was much better at detecting true positives and true negatives. The precision for the minority class is higher with the original data versus the resample data, meaning that the original data was better at detecting the users that were actually going to default. In terms of recall, however, the minority class metric using resample data was much better. Meaning that the resample data correctly classified a higher percentage of the truly defaulting borrowers. All in, the model using resample data was much better at detecting borrowers who are likely to default, than the model generated using the original imbalanced dataset.


The answer comes if we think about what oversampling does: it artificially increases the number of instances in the minority class. In this case, it increases the frequency of the 1 values. That trains the model to tend to correctly predict all the true 1 values (to have a higher recall). But, this happens at the expense of tending to overestimate the frequency of the 1 values (to have a lower precision).

We have this constant tradeoff when dealing with classification problems. Whether we should oversample the minority class depends on what matters the most in our context. If not correctly identifying power users of the app (that is, not correctly classifying a 1 value) costs us the first valuable customers, we might want to oversample the minority class. But if it's the other way around—that is, if flagging too many users as potential revenue generators will cost the company in advertising or customer-retention dollars—we might want to avoid oversampling.

The answer comes if we think about what oversampling does: it artificially increases the number of instances in the minority class. In this case, it increases the frequency of the 1 values. That trains the model to tend to correctly predict all the true 1 values (to have a higher recall). But, this happens at the expense of tending to overestimate the frequency of the 1 values (to have a lower precision).

We have this constant tradeoff when dealing with classification problems. Whether we should oversample the minority class depends on what matters the most in our context. If not correctly identifying power users of the app (that is, not correctly classifying a 1 value) costs us the first valuable customers, we might want to oversample the minority class. But if it's the other way around—that is, if flagging too many users as potential revenue generators will cost the company in advertising or customer-retention dollars—we might want to avoid oversampling.